### ISSUE TITLE
"No internet connection" when used with mitmproxy

### ISSUE THREAD

**Issue by sebastianha** [TimBroddin/stromer-api#4]
Hi,

I just tried to get my client id etc., but as soon as I enable mitmproxy the Stromer app tells me that there is a problem with the Internet connection.

Does this still work for you, or did they enable certificate pinning?

Regards, Sebastian

**Comment by sebastianha** [comment]
I just figured out that you can obtain the client_id and the client_secret from the app apk. Seems not to be unique to a user.

**Comment by TimBroddin** [comment]
Yeah, probably certificate pinning. Glad you find what you were looking for in the APK :)
