### ISSUE TITLE
Reset Trip

### ISSUE THREAD

**Issue by chaelli** [TimBroddin/stromer-api#5]
Hi @TimBroddin 

THANKS - this package is perfect for me to track charging issues!
I wish there was one more feature => resetting the trip-counters - so I could automatically reset the trip counters once I'm at home. Do you know if an API for this exists? (I could probably write the code, but I don't know if there's an api for it and how it works..

**Comment by TimBroddin** [comment]
You're welcome!

Is this possible in the app? I can't seem to find the option to do this?

**Comment by chaelli** [comment]
not that I could see :( so.. it might be a local-only function..  sorry, kind of expected it to be there as an API

**Comment by TimBroddin** [comment]
Too bad, this would be great functionality to have.
